{% set name = "numactl" %}
{% set version = "2.0.19" %}

package:
  name: libnuma-split
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: f2672a0381cb59196e9c246bf8bcc43d5568bc457700a697f1a1df762b9af884
  patches:
    # Skip specifically for CI, NUMA is not available in the kernel.
    - 0001-disable-tests.patch

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - autoconf
    - automake
    - coreutils
    - libtool
    - make

outputs:
  - name: libnuma
    script: install-libnuma.sh
    build:
      run_exports:
        - {{ pin_subpackage('libnuma', max_pin='x') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
        - autoconf
        - automake
        - coreutils
        - libtool
        - make
    test:
      commands:
        - test ! -f $PREFIX/lib/libnuma.a
        - test -f $PREFIX/include/numa.h
        - test -f $PREFIX/include/numacompat1.h
        - test -f $PREFIX/include/numaif.h
        - test -f $PREFIX/lib/libnuma${SHLIB_EXT}
        - test -f $PREFIX/lib/pkgconfig/numa.pc

  - name: {{ name }}
    build:
      run_exports:
        - {{ pin_subpackage('libnuma', max_pin='x') }}
    script: install-numactl.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
        - autoconf
        - automake
        - coreutils
        - libtool
        - make
      host:
        - libnuma {{ version.split('.')[0] }}
      run:
        - {{ pin_subpackage('libnuma', exact=True) }}
    test:
      commands:
        - numactl --version
        - test -f $PREFIX/bin/memhog
        - test -f $PREFIX/bin/migratepages
        - test -f $PREFIX/bin/migspeed
        - test -f $PREFIX/bin/numactl
        - test -f $PREFIX/bin/numademo
        - test -f $PREFIX/bin/numastat

about:
  home: https://github.com/numactl/numactl
  summary: NUMA support for Linux
  description: |
    Simple NUMA policy support. It consists of a numactl program to run other
    programs with a specific NUMA policy and a libnuma shared library
    ("NUMA API") to set NUMA policy in applications.
  license: LGPL-2.1-only AND GPL-2.0-only
  license_family: GPL
  license_file:
    - LICENSE.LGPL2.1
    - LICENSE.GPL2
  dev_url: https://github.com/numactl/numactl
  doc_url: https://linux.die.net/man/8/numactl

extra:
  feedstock-name: numactl
  recipe-maintainers:
    - kkraus14
    - chrisburr
    - zklaus
  skip-lints:
    - invalid_url
